/**
 * This file was generated by the Telegram Bot API generator.
 * Do not modify this file manually.
 * Use methods of 'client.core.ts' to setup client.
 **/

import * as types from './types';
import { client_fetch } from './core';

//<%
/**
 * _DESCRIPTION_
 */
export const _ENDPOINT_ = async (args: types._REQUEST_TYPE_): Promise<types._RESPONSE_TYPE_> => {
    return await client_fetch<types._REQUEST_TYPE_, types._RESPONSE_TYPE_>('_ENDPOINT_', args);
};
//%>
