/**
 * This file was generated by the Telegram Bot API generator.
 * Do not modify this file manually.
 * Use methods of 'client.core.ts' to set up client.
 **/

import * as simpleTypes from './simple-types';
import { client_fetch } from './core';

//<%
/**
 * _DESCRIPTION_
 */
export const _ENDPOINT_ = async (args: simpleTypes._REQUEST_TYPE_): Promise<simpleTypes._RESPONSE_TYPE_> => {
    return await client_fetch<simpleTypes._REQUEST_TYPE_, simpleTypes._RESPONSE_TYPE_>('_ENDPOINT_', args);
};
//%>
